[package]
name = "lact-client"
version = "0.10.1"
edition.workspace = true

[dependencies]
lact-schema = { path = "../lact-schema" }

anyhow = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["net", "sync", "time", "io-util"] }
futures = { workspace = true }

[target.'cfg(unix)'.dependencies]
amdgpu-sysfs = { workspace = true }
nix = { workspace = true, features = ["user"] }
